version: '3'
services:
  web:
    dash-init: .
    ports:
      - "3000:3000"
    # volumes:
    #   - vens-data: /app/dash-data
    volumes:
      - ./dash-data:/app/dash-data

# volumes:
#   vens-data:
#     driver: local
